### ISSUE TITLE
Generated records syntax

### ISSUE THREAD

**Issue by AlexeyRaga** [lucasteles/Strongly#8]
Hello!
First of all, thanks for an awesome library!

Unfortunately I have a problem interopping with other libraries, for example `GraphQL.Client`.

Turns out that when asked to generate `record`s the generated code looks like:

```csharp
[System.Diagnostics.DebuggerDisplay("{Value}", Type = "ProductId")]
#if NET7_0_OR_GREATER
readonly partial record struct ProductId 
#else
readonly partial record struct ProductId 
#endif
{
    public System.Guid Value { get; }

    public static readonly ProductId Empty = new ProductId(System.Guid.Empty);

    public static ProductId New() => new ProductId(System.Guid.NewGuid());
    
    public ProductId(System.Guid value)
    {
        Value = value;
    }
}
```

This somehow doesn't always work, but it would if we generated more conventional syntax:

```csharp
readonly partial record struct ProductId(Guid Value) ...
```

Would it be possible to have this change?
```

**Comment by lucasteles** [comment]
Can you create an isolated sample with the error?

**Comment by AlexeyRaga** [comment]
I think the problem is on the GraphQL lib side, which I have worked around.
